Notification = Error
executable = /users/sista/kkontras/Documents/Sleep_Project/condor_logs/script.sh
initialdir = /users/sista/kkontras/Documents/Sleep_Project/condor_logs
Log          = $(ClusterId)_$(Process).log
Output       = $(ClusterId)_$(Process).out
Error        = $(ClusterId)_$(Process).err

RequestCpus    = 16
RequestMemory  = 16G
+RequestWalltime = 259199
Request_GPUs   = 1
NiceUser = false
Requirements = ( CUDAGlobalMemoryMb > 5000 || CUDA0GlobalMemoryMb > 5000 ) && (machine != "stadius-nc-4.esat.kuleuven.be")
Queue Arguments from (
    /users/sista/kkontras/Documents/Sleep_Project/main_paper.py
    /users/sista/kkontras/Documents/Sleep_Project/main_paper_1.py
    /users/sista/kkontras/Documents/Sleep_Project/main_paper_2.py
    /users/sista/kkontras/Documents/Sleep_Project/main_paper_3.py
    /users/sista/kkontras/Documents/Sleep_Project/main_paper_4.py
    /users/sista/kkontras/Documents/Sleep_Project/main_paper_5.py
)